// Mock data for events
export const mockEvents = [
  {
    id: 1,
    title: "AI and Machine Learning Workshop",
    description: "Learn the fundamentals of AI and Machine Learning with hands-on exercises and real-world applications.",
    organiser_id: 2,
    organiser_name: "Tech University",
    category: "Technology",
    image_url: "/api/placeholder/400/225",
    start_date: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000), // 7 days from now
    end_date: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000 + 6 * 60 * 60 * 1000), // 6 hours later
    location: "Tech University Auditorium",
    max_capacity: 200,
    current_capacity: 142,
    status: "approved",
    price: 499,
    speakers: "Dr. John Smith, Dr. Sarah Johnson",
    schedule: "9:00 AM - 4:00 PM",
    created_at: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000),
    updated_at: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000),
  },
  {
    id: 2,
    title: "Web Development Bootcamp",
    description: "Comprehensive bootcamp covering modern web development technologies including React, Node.js, and more.",
    organiser_id: 2,
    organiser_name: "Code Academy",
    category: "Programming",
    image_url: "/api/placeholder/400/225",
    start_date: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000), // 14 days from now
    end_date: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000 + 8 * 60 * 60 * 1000), // 8 hours later
    location: "Code Academy Main Hall",
    max_capacity: 150,
    current_capacity: 89,
    status: "approved",
    price: 299,
    speakers: "Mike Johnson, Emily Davis",
    schedule: "10:00 AM - 6:00 PM",
    created_at: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
    updated_at: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
  },
  {
    id: 3,
    title: "Data Science Conference",
    description: "Join industry experts to discuss the latest trends in data science and analytics.",
    organiser_id: 3,
    organiser_name: "Data Insights Inc.",
    category: "Data Science",
    image_url: "/api/placeholder/400/225",
    start_date: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000), // 5 days from now
    end_date: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000 + 12 * 60 * 60 * 1000), // 12 hours later
    location: "Grand Convention Center",
    max_capacity: 500,
    current_capacity: 321,
    status: "approved",
    price: 799,
    speakers: "Dr. Robert Wilson, Lisa Chen",
    schedule: "9:00 AM - 9:00 PM",
    created_at: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000),
    updated_at: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000),
  },
  {
    id: 4,
    title: "Cybersecurity Essentials",
    description: "Learn essential cybersecurity practices for individuals and businesses.",
    organiser_id: 2,
    organiser_name: "SecureTech Solutions",
    category: "Security",
    image_url: "/api/placeholder/400/225",
    start_date: new Date(Date.now() + 21 * 24 * 60 * 60 * 1000), // 21 days from now
    end_date: new Date(Date.now() + 21 * 24 * 60 * 60 * 1000 + 4 * 60 * 60 * 1000), // 4 hours later
    location: "SecureTech Training Room",
    max_capacity: 75,
    current_capacity: 43,
    status: "approved",
    price: 199,
    speakers: "Alex Thompson",
    schedule: "2:00 PM - 6:00 PM",
    created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    updated_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
  },
  {
    id: 5,
    title: "Mobile App Development Workshop",
    description: "Build your first mobile app using React Native and Firebase.",
    organiser_id: 4,
    organiser_name: "App Masters",
    category: "Mobile Development",
    image_url: "/api/placeholder/400/225",
    start_date: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000), // 3 days from now
    end_date: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000 + 6 * 60 * 60 * 1000), // 6 hours later
    location: "App Masters Office",
    max_capacity: 100,
    current_capacity: 67,
    status: "approved",
    price: 399,
    speakers: "Jessica Williams, David Brown",
    schedule: "1:00 PM - 7:00 PM",
    created_at: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000),
    updated_at: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000),
  },
  {
    id: 6,
    title: "Cloud Computing Fundamentals",
    description: "Understanding cloud infrastructure and services with AWS, Azure, and Google Cloud.",
    organiser_id: 5,
    organiser_name: "Cloud Solutions",
    category: "Cloud Computing",
    image_url: "/api/placeholder/400/225",
    start_date: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000), // 10 days from now
    end_date: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000 + 8 * 60 * 60 * 1000), // 8 hours later
    location: "Cloud Solutions Training Center",
    max_capacity: 120,
    current_capacity: 88,
    status: "approved",
    price: 599,
    speakers: "Michael Johnson, Sarah Lee",
    schedule: "9:00 AM - 5:00 PM",
    created_at: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000),
    updated_at: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000),
  },
];

// Mock data for users
export const mockUsers = [
  {
    id: 1,
    email: "admin@eventify.com",
    name: "Admin User",
    role: "admin",
    phone: "9999999999",
    college: "Admin College",
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 2,
    email: "organiser@eventify.com",
    name: "Organiser User",
    role: "organiser",
    phone: "8888888888",
    college: "Organiser Institute",
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 3,
    email: "attendee@eventify.com",
    name: "Attendee User",
    role: "attendee",
    phone: "7777777777",
    college: "Attendee University",
    created_at: new Date(),
    updated_at: new Date(),
  },
];

// Mock data for registrations
export const mockRegistrations = [
  {
    id: 1,
    event_id: 1,
    user_id: 3,
    status: "confirmed",
    registration_date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    price: 499,
  },
  {
    id: 2,
    event_id: 2,
    user_id: 3,
    status: "confirmed",
    registration_date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    price: 299,
  },
  {
    id: 3,
    event_id: 3,
    user_id: 3,
    status: "pending",
    registration_date: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    price: 799,
  },
];